---
- name: Listen for netbox events on a webhook
  hosts: all
  sources:
    - name: Listen for events
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4999
  rules:
    - name: update vm
      condition: event.meta is defined and event.payload.event == "updated" and event.payload.model == "virtualmachine"
      action:
        run_job_template:
          organization: "Default"
          name: "update vm"
          job_args:
            extra_vars:
              data: "{{ event.payload.data }}"